DROP SEQUENCE "DB_name"."EMPLOYE_SEQ";
DROP SEQUENCE "DB_name"."REFCONTENU_SEQ";
DROP SEQUENCE "DB_name"."REFCONTRAT_SEQ";
DROP SEQUENCE "DB_name"."REFDIFFUSION_SEQ";
DROP SEQUENCE "DB_name"."REFEQUIPEMENT_SEQ";
DROP TABLE "DB_name"."CONTENUS" cascade constraints;
DROP TABLE "DB_name"."CONTRATS" cascade constraints;
DROP TABLE "DB_name"."DIFFUSER" cascade constraints;
DROP TABLE "DB_name"."DIFFUSIONS" cascade constraints;
DROP TABLE "DB_name"."EMPLOYES" cascade constraints;
DROP TABLE "DB_name"."EQUIPEMENTS" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence EMPLOYE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DB_name"."EMPLOYE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REFCONTENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DB_name"."REFCONTENU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REFCONTRAT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DB_name"."REFCONTRAT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REFDIFFUSION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DB_name"."REFDIFFUSION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REFEQUIPEMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DB_name"."REFEQUIPEMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CONTENUS
--------------------------------------------------------

  CREATE TABLE "DB_name"."CONTENUS" 
   (	"REFCONTENU" NUMBER, 
	"TITRE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"AFFICHE" BLOB, 
	"VIDEO" BLOB, 
	"DUREE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"DATE_PRODUCTION" DATE, 
	"REFCONTRAT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("AFFICHE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("VIDEO") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CONTRATS
--------------------------------------------------------

  CREATE TABLE "DB_name"."CONTRATS" 
   (	"REFCONTRAT" NUMBER, 
	"TITRE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"TRANSACTION" VARCHAR2(20 BYTE), 
	"BUDGET" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DIFFUSER
--------------------------------------------------------

  CREATE TABLE "DB_name"."DIFFUSER" 
   (	"REFDIFFUSION" NUMBER, 
	"REFCONTENU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DIFFUSIONS
--------------------------------------------------------

  CREATE TABLE "DB_name"."DIFFUSIONS" 
   (	"REFDIFFUSION" NUMBER, 
	"DATE_DIFFUSION" DATE, 
	"TEMP_DEBUT" TIMESTAMP (6), 
	"TEMP_FIN" TIMESTAMP (6), 
	"STATUS" VARCHAR2(50 BYTE), 
	"ETAT" VARCHAR2(50 BYTE), 
	"IDEMPLOYE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "DB_name"."EMPLOYES" 
   (	"IDEMPLOYE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" DATE, 
	"PHOTO_PROFILE" BLOB, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TELEPHONE" NUMBER, 
	"GENRE" VARCHAR2(10 BYTE), 
	"DATE_EMBAUCHE" DATE, 
	"SALAIRE" NUMBER, 
	"ROLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PHOTO_PROFILE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENTS
--------------------------------------------------------

  CREATE TABLE "DB_name"."EQUIPEMENTS" 
   (	"REFEQUIPEMENT" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"COUT" VARCHAR2(20 BYTE), 
	"DATE_ACHAT" DATE, 
	"DISPONIBILITE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"LOCALISATION" VARCHAR2(20 BYTE), 
	"DATE_MAINTENANCE" DATE, 
	"IDEMPLOYE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DB_name.CONTENUS
SET DEFINE OFF;
REM INSERTING into DB_name.CONTRATS
SET DEFINE OFF;
REM INSERTING into DB_name.DIFFUSER
SET DEFINE OFF;
REM INSERTING into DB_name.DIFFUSIONS
SET DEFINE OFF;
REM INSERTING into DB_name.EMPLOYES
SET DEFINE OFF;
REM INSERTING into DB_name.EQUIPEMENTS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index EMPLOYES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_name"."EMPLOYES_PK" ON "DB_name"."EMPLOYES" ("IDEMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_name"."EQUIPEMENTS_PK" ON "DB_name"."EQUIPEMENTS" ("REFEQUIPEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONTENUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_name"."CONTENUS_PK" ON "DB_name"."CONTENUS" ("REFCONTENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DIFFUSIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_name"."DIFFUSIONS_PK" ON "DB_name"."DIFFUSIONS" ("REFDIFFUSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DIFFUSER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_name"."DIFFUSER_PK" ON "DB_name"."DIFFUSER" ("REFDIFFUSION", "REFCONTENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONTRATS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB_name"."CONTRATS_PK" ON "DB_name"."CONTRATS" ("REFCONTRAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger EMPLOYE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DB_name"."EMPLOYE_TRIGGER" 
BEFORE INSERT ON employes
FOR EACH ROW
BEGIN
  SELECT employe_seq.NEXTVAL
  INTO   :NEW.IDEMPLOYE
  FROM   dual;
END;
/
ALTER TRIGGER "DB_name"."EMPLOYE_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REFCONTENU_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DB_name"."REFCONTENU_TRIGGER" 
BEFORE INSERT ON contenus
FOR EACH ROW
BEGIN
  SELECT refcontenu_seq.NEXTVAL
  INTO   :NEW.REFCONTENU
  FROM   dual;
END;
/
ALTER TRIGGER "DB_name"."REFCONTENU_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REFCONTRAT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DB_name"."REFCONTRAT_TRIGGER" 
BEFORE INSERT ON contrats
FOR EACH ROW
BEGIN
  SELECT refcontrat_seq.NEXTVAL
  INTO   :NEW.REFCONTRAT
  FROM   dual;
END;
/
ALTER TRIGGER "DB_name"."REFCONTRAT_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REFDIFFUSION_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DB_name"."REFDIFFUSION_TRIGGER" 
BEFORE INSERT ON diffusions
FOR EACH ROW
BEGIN
  SELECT refdiffusion_seq.NEXTVAL
  INTO   :NEW.REFDIFFUSION
  FROM   dual;
END;
/
ALTER TRIGGER "DB_name"."REFDIFFUSION_TRIGGER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REFEQUIPEMENT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DB_name"."REFEQUIPEMENT_TRIGGER" 
BEFORE INSERT ON equipements
FOR EACH ROW
BEGIN
  SELECT refequipement_seq.NEXTVAL
  INTO   :NEW.REFEQUIPEMENT
  FROM   dual;
END;
/
ALTER TRIGGER "DB_name"."REFEQUIPEMENT_TRIGGER" ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE "DB_name"."EQUIPEMENTS" ADD CONSTRAINT "EQUIPEMENTS_PK" PRIMARY KEY ("REFEQUIPEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DB_name"."EQUIPEMENTS" MODIFY ("REFEQUIPEMENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTRATS
--------------------------------------------------------

  ALTER TABLE "DB_name"."CONTRATS" ADD CONSTRAINT "CONTRATS_PK" PRIMARY KEY ("REFCONTRAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DB_name"."CONTRATS" MODIFY ("REFCONTRAT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "DB_name"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_PK" PRIMARY KEY ("IDEMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DIFFUSER
--------------------------------------------------------

  ALTER TABLE "DB_name"."DIFFUSER" ADD CONSTRAINT "DIFFUSER_PK" PRIMARY KEY ("REFDIFFUSION", "REFCONTENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DB_name"."DIFFUSER" MODIFY ("REFCONTENU" NOT NULL ENABLE);
  ALTER TABLE "DB_name"."DIFFUSER" MODIFY ("REFDIFFUSION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTENUS
--------------------------------------------------------

  ALTER TABLE "DB_name"."CONTENUS" ADD CONSTRAINT "CONTENUS_PK" PRIMARY KEY ("REFCONTENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DB_name"."CONTENUS" MODIFY ("REFCONTENU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DIFFUSIONS
--------------------------------------------------------

  ALTER TABLE "DB_name"."DIFFUSIONS" ADD CONSTRAINT "DIFFUSIONS_PK" PRIMARY KEY ("REFDIFFUSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DB_name"."DIFFUSIONS" MODIFY ("REFDIFFUSION" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CONTENUS
--------------------------------------------------------

  ALTER TABLE "DB_name"."CONTENUS" ADD CONSTRAINT "CONTENUS_FK1" FOREIGN KEY ("REFCONTRAT")
	  REFERENCES "DB_name"."CONTRATS" ("REFCONTRAT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIFFUSER
--------------------------------------------------------

  ALTER TABLE "DB_name"."DIFFUSER" ADD CONSTRAINT "DIFFUSER_FK1" FOREIGN KEY ("REFDIFFUSION")
	  REFERENCES "DB_name"."DIFFUSIONS" ("REFDIFFUSION") ENABLE;
  ALTER TABLE "DB_name"."DIFFUSER" ADD CONSTRAINT "DIFFUSER_FK2" FOREIGN KEY ("REFCONTENU")
	  REFERENCES "DB_name"."CONTENUS" ("REFCONTENU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIFFUSIONS
--------------------------------------------------------

  ALTER TABLE "DB_name"."DIFFUSIONS" ADD CONSTRAINT "DIFFUSIONS_FK1" FOREIGN KEY ("IDEMPLOYE")
	  REFERENCES "DB_name"."EMPLOYES" ("IDEMPLOYE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE "DB_name"."EQUIPEMENTS" ADD CONSTRAINT "EQUIPEMENTS_FK1" FOREIGN KEY ("IDEMPLOYE")
	  REFERENCES "DB_name"."EMPLOYES" ("IDEMPLOYE") ENABLE;
