--------------------------------------------------------
DROP SEQUENCE EMPLOYE_SEQ;
DROP SEQUENCE REFCONTENU_SEQ;
DROP SEQUENCE REFCONTRAT_SEQ;
DROP SEQUENCE REFDIFFUSION_SEQ;
DROP SEQUENCE REFEQUIPEMENT_SEQ;
DROP TABLE CONTENUS cascade constraints;
DROP TABLE CONTRATS cascade constraints;
DROP TABLE DIFFUSER cascade constraints;
DROP TABLE DIFFUSIONS cascade constraints;
DROP TABLE EMPLOYES cascade constraints;
DROP TABLE EQUIPEMENTS cascade constraints;
--------------------------------------------------------
--  DDL for Sequence EMPLOYE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  EMPLOYE_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REFCONTENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  REFCONTENU_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REFCONTRAT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  REFCONTRAT_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REFDIFFUSION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  REFDIFFUSION_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REFEQUIPEMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  REFEQUIPEMENT_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CONTENUS
--------------------------------------------------------

  CREATE TABLE CONTENUS 
   (	REFCONTENU NUMBER, 
	TITRE VARCHAR2(20 BYTE), 
	DESCRIPTION VARCHAR2(250 BYTE), 
	TYPE VARCHAR2(20 BYTE), 
	AFFICHE BLOB, 
	VIDEO BLOB, 
	DUREE VARCHAR2(20 BYTE), 
	ETAT VARCHAR2(20 BYTE), 
	DATE_PRODUCTION DATE, 
	REFCONTRAT NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM 
 LOB (AFFICHE) STORE AS BASICFILE (
  TABLESPACE SYSTEM ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB (VIDEO) STORE AS BASICFILE (
  TABLESPACE SYSTEM ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CONTRATS
--------------------------------------------------------

  CREATE TABLE CONTRATS 
   (	REFCONTRAT NUMBER, 
	TITRE VARCHAR2(20 BYTE), 
	DESCRIPTION VARCHAR2(500 BYTE), 
	TYPE VARCHAR2(20 BYTE), 
	DATE_DEBUT DATE, 
	DATE_FIN DATE, 
	TRANSACTION VARCHAR2(20 BYTE), 
	BUDGET NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;
--------------------------------------------------------
--  DDL for Table DIFFUSER
--------------------------------------------------------

  CREATE TABLE DIFFUSER 
   (	REFDIFFUSION NUMBER, 
	REFCONTENU NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;
--------------------------------------------------------
--  DDL for Table DIFFUSIONS
--------------------------------------------------------

  CREATE TABLE DIFFUSIONS 
   (	REFDIFFUSION NUMBER, 
	DATE_DIFFUSION DATE, 
	TEMP_DEBUT TIMESTAMP (6), 
	TEMP_FIN TIMESTAMP (6), 
	STATUS VARCHAR2(50 BYTE), 
	ETAT VARCHAR2(50 BYTE), 
	IDEMPLOYE NUMBER, 
	REFCONTENU_PRECEDENT NUMBER, 
	REFCONTENU_SUIVANT NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE EMPLOYES 
   (	IDEMPLOYE NUMBER, 
	NOM VARCHAR2(20 BYTE), 
	PRENOM VARCHAR2(20 BYTE), 
	DATE_NAISSANCE DATE, 
	PHOTO_PROFILE BLOB, 
	EMAIL VARCHAR2(100 BYTE), 
	TELEPHONE NUMBER, 
	GENRE VARCHAR2(10 BYTE), 
	DATE_EMBAUCHE DATE, 
	SALAIRE NUMBER, 
	ROLE VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM 
 LOB (PHOTO_PROFILE) STORE AS BASICFILE (
  TABLESPACE SYSTEM ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENTS
--------------------------------------------------------

  CREATE TABLE EQUIPEMENTS 
   (	REFEQUIPEMENT NUMBER, 
	NOM VARCHAR2(20 BYTE), 
	TYPE VARCHAR2(20 BYTE), 
	COUT VARCHAR2(20 BYTE), 
	DATE_ACHAT DATE, 
	DISPONIBILITE VARCHAR2(20 BYTE), 
	ETAT VARCHAR2(20 BYTE), 
	LOCALISATION VARCHAR2(20 BYTE), 
	DATE_MAINTENANCE DATE, 
	IDEMPLOYE NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;
REM INSERTING into FARES.CONTENUS
SET DEFINE OFF;
REM INSERTING into FARES.CONTRATS
SET DEFINE OFF;
REM INSERTING into FARES.DIFFUSER
SET DEFINE OFF;
REM INSERTING into FARES.DIFFUSIONS
SET DEFINE OFF;
REM INSERTING into FARES.EMPLOYES
SET DEFINE OFF;
REM INSERTING into FARES.EQUIPEMENTS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index EQUIPEMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX EQUIPEMENTS_PK ON EQUIPEMENTS (REFEQUIPEMENT) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;
--------------------------------------------------------
--  DDL for Index DIFFUSER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX DIFFUSER_PK ON DIFFUSER (REFDIFFUSION, REFCONTENU) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;
--------------------------------------------------------
--  DDL for Index CONTRATS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX CONTRATS_PK ON CONTRATS (REFCONTRAT) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;
--------------------------------------------------------
--  DDL for Index EMPLOYES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX EMPLOYES_PK ON EMPLOYES (IDEMPLOYE) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;
--------------------------------------------------------
--  DDL for Index CONTENUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX CONTENUS_PK ON CONTENUS (REFCONTENU) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;
--------------------------------------------------------
--  DDL for Index DIFFUSIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX DIFFUSIONS_PK ON DIFFUSIONS (REFDIFFUSION) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;
--------------------------------------------------------
--  DDL for Index EMAIL_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX EMAIL_UNIQUE ON EMPLOYES (EMAIL) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM ;
--------------------------------------------------------
--  DDL for Trigger EMPLOYE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER EMPLOYE_TRIGGER 
BEFORE INSERT ON employes
FOR EACH ROW
BEGIN
  SELECT employe_seq.NEXTVAL
  INTO   :NEW.IDEMPLOYE
  FROM   dual;
END;
/
ALTER TRIGGER EMPLOYE_TRIGGER ENABLE;
--------------------------------------------------------
--  DDL for Trigger REFCONTENU_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER REFCONTENU_TRIGGER 
BEFORE INSERT ON contenus
FOR EACH ROW
BEGIN
  SELECT refcontenu_seq.NEXTVAL
  INTO   :NEW.REFCONTENU
  FROM   dual;
END;
/
ALTER TRIGGER REFCONTENU_TRIGGER ENABLE;
--------------------------------------------------------
--  DDL for Trigger REFCONTRAT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER REFCONTRAT_TRIGGER 
BEFORE INSERT ON contrats
FOR EACH ROW
BEGIN
  SELECT refcontrat_seq.NEXTVAL
  INTO   :NEW.REFCONTRAT
  FROM   dual;
END;
/
ALTER TRIGGER REFCONTRAT_TRIGGER ENABLE;
--------------------------------------------------------
--  DDL for Trigger REFDIFFUSION_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER REFDIFFUSION_TRIGGER 
BEFORE INSERT ON diffusions
FOR EACH ROW
BEGIN
  SELECT refdiffusion_seq.NEXTVAL
  INTO   :NEW.REFDIFFUSION
  FROM   dual;
END;
/
ALTER TRIGGER REFDIFFUSION_TRIGGER ENABLE;
--------------------------------------------------------
--  DDL for Trigger REFEQUIPEMENT_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER REFEQUIPEMENT_TRIGGER 
BEFORE INSERT ON equipements
FOR EACH ROW
BEGIN
  SELECT refequipement_seq.NEXTVAL
  INTO   :NEW.REFEQUIPEMENT
  FROM   dual;
END;
/
ALTER TRIGGER REFEQUIPEMENT_TRIGGER ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE EQUIPEMENTS ADD CONSTRAINT EQUIPEMENTS_PK PRIMARY KEY (REFEQUIPEMENT)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM  ENABLE;
  ALTER TABLE EQUIPEMENTS MODIFY (REFEQUIPEMENT NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTRATS
--------------------------------------------------------

  ALTER TABLE CONTRATS ADD CONSTRAINT CONTRATS_PK PRIMARY KEY (REFCONTRAT)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM  ENABLE;
  ALTER TABLE CONTRATS MODIFY (REFCONTRAT NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE EMPLOYES ADD CONSTRAINT EMAIL_UNIQUE UNIQUE (EMAIL)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM  ENABLE;
  ALTER TABLE EMPLOYES ADD CONSTRAINT EMPLOYES_PK PRIMARY KEY (IDEMPLOYE)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM  ENABLE;
--------------------------------------------------------
--  Constraints for Table DIFFUSER
--------------------------------------------------------

  ALTER TABLE DIFFUSER ADD CONSTRAINT DIFFUSER_PK PRIMARY KEY (REFDIFFUSION, REFCONTENU)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM  ENABLE;
  ALTER TABLE DIFFUSER MODIFY (REFCONTENU NOT NULL ENABLE);
  ALTER TABLE DIFFUSER MODIFY (REFDIFFUSION NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTENUS
--------------------------------------------------------

  ALTER TABLE CONTENUS ADD CONSTRAINT CONTENUS_PK PRIMARY KEY (REFCONTENU)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM  ENABLE;
  ALTER TABLE CONTENUS MODIFY (REFCONTENU NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DIFFUSIONS
--------------------------------------------------------

  ALTER TABLE DIFFUSIONS ADD CONSTRAINT DIFFUSIONS_PK PRIMARY KEY (REFDIFFUSION)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE SYSTEM  ENABLE;
  ALTER TABLE DIFFUSIONS MODIFY (REFDIFFUSION NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CONTENUS
--------------------------------------------------------

  ALTER TABLE CONTENUS ADD CONSTRAINT CONTENUS_FK1 FOREIGN KEY (REFCONTRAT)
	  REFERENCES CONTRATS (REFCONTRAT) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIFFUSER
--------------------------------------------------------

  ALTER TABLE DIFFUSER ADD CONSTRAINT DIFFUSER_FK1 FOREIGN KEY (REFDIFFUSION)
	  REFERENCES DIFFUSIONS (REFDIFFUSION) ENABLE;
  ALTER TABLE DIFFUSER ADD CONSTRAINT DIFFUSER_FK2 FOREIGN KEY (REFCONTENU)
	  REFERENCES CONTENUS (REFCONTENU) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIFFUSIONS
--------------------------------------------------------

  ALTER TABLE DIFFUSIONS ADD CONSTRAINT DIFFUSIONS_FK1 FOREIGN KEY (IDEMPLOYE)
	  REFERENCES EMPLOYES (IDEMPLOYE) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE EQUIPEMENTS ADD CONSTRAINT EQUIPEMENTS_FK1 FOREIGN KEY (IDEMPLOYE)
	  REFERENCES EMPLOYES (IDEMPLOYE) ENABLE;